# This is a basic workflow for getting started with Actions
name: testing
# Create git actions
on:
# Allow to manually run workflow actions
  workflow_dispatch:
# Listen for a push event and trigger an action
  push: 
    branches: [ master ]
# Define jobs
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout this commit
        uses: actions/checkout@v2
      - name: run one line command
        run: echo Hello World
      
      
